version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/files:/app/files
      - ./backend/students.csv:/app/students.csv
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - blockchain-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - blockchain-network

networks:
  blockchain-network:
    driver: bridge

volumes:
  uploaded_files:
